title: Emilio Rosa

theme: jekyll-theme-midnight
markdown: kramdown

baseurl: /

paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

sass:
  sass_dir: /assets/css/_sass
  style: compressed
  
include:
  - _pages
  
exclude:
  - README.md
  - CNAME
  
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank

