version: '3'

services:
  app:
    image: node:20
    ports:
      - 4321:4321
    working_dir: /app
    command: >
      sh -c "npm i &&
              npm run dev -- --host 0.0.0.0"
    volumes:
      - ./:/app